#!/bin/bash

hyprpaper &
{%- if device == "desktop" %}
  ignis init &
{% elif device == "laptop" %}
  quickshell &
{% endif -%}
wl-paste --watch cliphist store &
{{bombadil_cmd}} &
hyprctl dispatch workspace 1
